services:
  pipelinepredict-api:
    build: .
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      SERVER_PORT: ${API_PORT}
      SPRING_DATASOURCE_URL: ${API_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${API_USER}
      SPRING_DATASOURCE_PASSWORD: ${API_PASSWORD}
    networks:
      - pipelinepredict-net
    restart: unless-stopped

networks:
  pipelinepredict-net:
    external: true
